//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModMaker.Lua {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModMaker.Lua.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object with the name &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given binary operation is not valid..
        /// </summary>
        internal static string BadBinOp {
            get {
                return ResourceManager.GetString("BadBinOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast an object of type {0} to the type {1}..
        /// </summary>
        internal static string BadCast {
            get {
                return ResourceManager.GetString("BadCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of a &apos;{0}&apos; must be a {1}..
        /// </summary>
        internal static string BadIndexType {
            get {
                return ResourceManager.GetString("BadIndexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number format..
        /// </summary>
        internal static string BadNumberFormat {
            get {
                return ResourceManager.GetString("BadNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type marked with LuaIgnoreAttribute with a given BehavesAs must inherit from that type..
        /// </summary>
        internal static string BehavesAsMustDeriveType {
            get {
                return ResourceManager.GetString("BehavesAsMustDeriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variable marked with LuaIgnoreAttribute with a given BehavesAs must inherit from that type..
        /// </summary>
        internal static string BehavesAsMustDeriveVar {
            get {
                return ResourceManager.GetString("BehavesAsMustDeriveVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to perform arithmetic on a &apos;{0}&apos; value..
        /// </summary>
        internal static string CannotArithmetic {
            get {
                return ResourceManager.GetString("CannotArithmetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to call a &apos;{0}&apos; type..
        /// </summary>
        internal static string CannotCall {
            get {
                return ResourceManager.GetString("CannotCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot contain a null value..
        /// </summary>
        internal static string CannotContainNull {
            get {
                return ResourceManager.GetString("CannotContainNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attemt to enumerate a &apos;{0}&apos; type..
        /// </summary>
        internal static string CannotEnumerate {
            get {
                return ResourceManager.GetString("CannotEnumerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot hide member &apos;{0}&apos; defined in base class &apos;{1}&apos;..
        /// </summary>
        internal static string CannotHideMember {
            get {
                return ResourceManager.GetString("CannotHideMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to index a &apos;{0}&apos; type..
        /// </summary>
        internal static string CannotIndex {
            get {
                return ResourceManager.GetString("CannotIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot override property &apos;{0}&apos; because it is not virtual..
        /// </summary>
        internal static string CannotOverrideProperty {
            get {
                return ResourceManager.GetString("CannotOverrideProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify the overload of a {0}..
        /// </summary>
        internal static string CannotUseOverload {
            get {
                return ResourceManager.GetString("CannotUseOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index must be positive and less than the number of chunks loaded..
        /// </summary>
        internal static string ChunkOutOfRange {
            get {
                return ResourceManager.GetString("ChunkOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to a constant property..
        /// </summary>
        internal static string ConstantProperty {
            get {
                return ResourceManager.GetString("ConstantProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constructor can only be a function..
        /// </summary>
        internal static string CtorMustBeFunc {
            get {
                return ResourceManager.GetString("CtorMustBeFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current class does not derrive from type &apos;{0}&apos;..
        /// </summary>
        internal static string CurrentDoesNotDerive {
            get {
                return ResourceManager.GetString("CurrentDoesNotDerive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must define at least one name..
        /// </summary>
        internal static string DefineAtLeastOneName {
            get {
                return ResourceManager.GetString("DefineAtLeastOneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is already defined as a Method..
        /// </summary>
        internal static string DefinedAsMethod {
            get {
                return ResourceManager.GetString("DefinedAsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given type must derive from delegate..
        /// </summary>
        internal static string DeriveFromDelegate {
            get {
                return ResourceManager.GetString("DeriveFromDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &apos;{0}&apos; does not implement an interface with the name &apos;{1}&apos;..
        /// </summary>
        internal static string DoesNotImplement {
            get {
                return ResourceManager.GetString("DoesNotImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while resolving labels, make sure not to change UserData during compilation..
        /// </summary>
        internal static string ErrorResolveLabel {
            get {
                return ResourceManager.GetString("ErrorResolveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an overload specified with the index &apos;{0}&apos;..
        /// </summary>
        internal static string ExistingOverload {
            get {
                return ResourceManager.GetString("ExistingOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a function call after specifying an overload..
        /// </summary>
        internal static string FunctionCallAfterOverload {
            get {
                return ResourceManager.GetString("FunctionCallAfterOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions cannot have names when used as expressions..
        /// </summary>
        internal static string FunctionCantHaveName {
            get {
                return ResourceManager.GetString("FunctionCantHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot index an expression..
        /// </summary>
        internal static string IndexAfterExpression {
            get {
                return ResourceManager.GetString("IndexAfterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use an indexer after an instance call..
        /// </summary>
        internal static string IndexerAfterInstance {
            get {
                return ResourceManager.GetString("IndexerAfterInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use indexers(.) in local definition..
        /// </summary>
        internal static string IndexerLocalMethod {
            get {
                return ResourceManager.GetString("IndexerLocalMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot define instance methods for local methods..
        /// </summary>
        internal static string InstanceLocalMethod {
            get {
                return ResourceManager.GetString("InstanceLocalMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance function call missing arguments..
        /// </summary>
        internal static string InstanceMissingArgs {
            get {
                return ResourceManager.GetString("InstanceMissingArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} definition..
        /// </summary>
        internal static string InvalidDefinition {
            get {
                return ResourceManager.GetString("InvalidDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence &apos;\{0}&apos;..
        /// </summary>
        internal static string InvalidEscape {
            get {
                return ResourceManager.GetString("InvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A literal must be of type bool, double, string, or be null..
        /// </summary>
        internal static string InvalidLiteralType {
            get {
                return ResourceManager.GetString("InvalidLiteralType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use unary minus on a string, bool, or nil..
        /// </summary>
        internal static string InvalidUnary {
            get {
                return ResourceManager.GetString("InvalidUnary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A label with the name &apos;{0}&apos; is already defined in this block..
        /// </summary>
        internal static string LabelAlreadyDefined {
            get {
                return ResourceManager.GetString("LabelAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate label &apos;{0}&apos; for goto item..
        /// </summary>
        internal static string LabelNotFound {
            get {
                return ResourceManager.GetString("LabelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Start, Limit, and Step of a for loop must result in numbers..
        /// </summary>
        internal static string LoopMustBeNumbers {
            get {
                return ResourceManager.GetString("LoopMustBeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; defines more than one member named &apos;{1}&apos;..
        /// </summary>
        internal static string ManyMembersFound {
            get {
                return ResourceManager.GetString("ManyMembersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; has already a been assigned a default value..
        /// </summary>
        internal static string MemberHasDefault {
            get {
                return ResourceManager.GetString("MemberHasDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; has already a been assigned a type..
        /// </summary>
        internal static string MemberHasType {
            get {
                return ResourceManager.GetString("MemberHasType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing end of {0}..
        /// </summary>
        internal static string MissingEnd {
            get {
                return ResourceManager.GetString("MissingEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register a multicast delegate, must register each individually..
        /// </summary>
        internal static string MulticastNotSupported {
            get {
                return ResourceManager.GetString("MulticastNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; is defined as a method and must be set to a Lua function..
        /// </summary>
        internal static string MustBeFunction {
            get {
                return ResourceManager.GetString("MustBeFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be on a &apos;{0}&apos; when calling {1}..
        /// </summary>
        internal static string MustBeOn {
            get {
                return ResourceManager.GetString("MustBeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LuaValue types must inherit ILuaValueVisitor..
        /// </summary>
        internal static string MustHaveVisitor {
            get {
                return ResourceManager.GetString("MustHaveVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must give a name or expression for a variable definition..
        /// </summary>
        internal static string NameOrExpForVar {
            get {
                return ResourceManager.GetString("NameOrExpForVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not contain a definition of member &apos;{1}&apos;..
        /// </summary>
        internal static string NoMemberFound {
            get {
                return ResourceManager.GetString("NoMemberFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only specify one instance call..
        /// </summary>
        internal static string OneInstanceCall {
            get {
                return ResourceManager.GetString("OneInstanceCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numbers are allowed after the grave(`) when specifying an overload..
        /// </summary>
        internal static string OnlyNumbersInOverload {
            get {
                return ResourceManager.GetString("OnlyNumbersInOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only variables can be passed by-reference..
        /// </summary>
        internal static string OnlyVarByReference {
            get {
                return ResourceManager.GetString("OnlyVarByReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overload function call missing arguments..
        /// </summary>
        internal static string OverloadMissingArgs {
            get {
                return ResourceManager.GetString("OverloadMissingArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only specify one grave(`) in an overload..
        /// </summary>
        internal static string OverloadOneGrave {
            get {
                return ResourceManager.GetString("OverloadOneGrave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified overload is greater than the number defined..
        /// </summary>
        internal static string OverloadOutOfRange {
            get {
                return ResourceManager.GetString("OverloadOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values in a property table must be functions..
        /// </summary>
        internal static string PropTableFuncs {
            get {
                return ResourceManager.GetString("PropTableFuncs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property table can only contain a &apos;get&apos; and/or a &apos;set&apos; items..
        /// </summary>
        internal static string PropTableGetSet {
            get {
                return ResourceManager.GetString("PropTableGetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify the settings after it is registered to an Environment..
        /// </summary>
        internal static string ReadonlySettings {
            get {
                return ResourceManager.GetString("ReadonlySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;ref&apos; keyword can only have one argument..
        /// </summary>
        internal static string RefOneArgument {
            get {
                return ResourceManager.GetString("RefOneArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return statement must be the last statement in a block..
        /// </summary>
        internal static string ReturnAtEnd {
            get {
                return ResourceManager.GetString("ReturnAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token &apos;{0}&apos;, expecting end of file..
        /// </summary>
        internal static string TokenEOF {
            get {
                return ResourceManager.GetString("TokenEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token &apos;{0}&apos; in {1} definition..
        /// </summary>
        internal static string TokenInvalid {
            get {
                return ResourceManager.GetString("TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token &apos;{0}&apos; in {1} definition, expecting &apos;{2}&apos;..
        /// </summary>
        internal static string TokenInvalidExpecting {
            get {
                return ResourceManager.GetString("TokenInvalidExpecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token &apos;{0}&apos; in {1} definition, expecting &apos;{2}&apos; or &apos;{3}&apos;..
        /// </summary>
        internal static string TokenInvalidExpecting2 {
            get {
                return ResourceManager.GetString("TokenInvalidExpecting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token in &apos;{0}&apos; definition, &apos;{1}&apos; is not a name..
        /// </summary>
        internal static string TokenNotAName {
            get {
                return ResourceManager.GetString("TokenNotAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name, &apos;{0}&apos; is reserved..
        /// </summary>
        internal static string TokenReserved {
            get {
                return ResourceManager.GetString("TokenReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token &apos;{0}&apos;, expecting start of statement..
        /// </summary>
        internal static string TokenStatement {
            get {
                return ResourceManager.GetString("TokenStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file in {0}..
        /// </summary>
        internal static string UnexpectedEOF {
            get {
                return ResourceManager.GetString("UnexpectedEOF", resourceCulture);
            }
        }
    }
}
